FORMAT: 1A
HOST: http://api.medselfed.com

FORMAT: 1A

# MedSelfEd API
The MedSelfEd  API is resource available on the MedSelfEd patient engagement platform 
that can be integrated with your website, CMS or LMS through MedSelfEd APIs. MedSelfEd API 
Offerings enable organizations; patient educators and application developers to connect 
to MSE content from anywhere in real-time.

## Authentication
Consumer Application authentication is the process of verifying the identity of a user or 
service that seeks access to MedSelfEd API. This process ensures that request made by 
the user of the account (as specified in the request), is genuine and allowed to interact 
with the MedSelfEd API

## Content Types
Where applicable this API uses the [application/json](http://en.wikipedia.org/wiki/JSON) 
media-type to represent resources states and affordances.

Requests with a message-body are using plain JSON to set or update resource states.

## Error States
The common [HTTP Response Status Codes](https://github.com/for-GET/know-your-http-well/blob/master/status-codes.md) are used.


# Group Procedures API
Procedures-related resources of *Procedures API*.


# GET All Procedures [/v1/procedures]
Procedures API entry point, responds with all available procedures.

This resource does not have any attributes. Instead it offers the initial API affordances in the form of links to available media types.

Example Request

To make a request to the API run the following command at a terminal prompt.

`````
curl 'http://api.medselfed.com/v1/procedures?apikey=111223' 
`````

## Retrieve all Procedures [GET]

+ Response 200 (application/json)
    + Headers

    + Body

        {
          "class": [
            "root"
          ],
          "properties": [
            {
              "id": "549-001",
              "langId": "en",
              "siteId": "preop",
              "name": "Vasectomy Surgery",
              "translations": [
                {
                  "langId": "en",
                  "name": "Vasectomy Surgery",
                  "content": "Vasectomy Surgery",
                  "type": "application/json",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-001"
                },
                {
                  "langId": "es",
                  "name": "Vasectomía",
                  "content": "Vasectomía",
                  "type": "application/json",
                  "href": "http://api.medselfed.com/v1/es/procedures/549-001"
                }
              ],
              "links": [
                {
                  "type": "application/json",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-001"
                },
                {
                  "type": "image/jpg",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-001/image.jpg"
                },
                {
                  "type": "video/mp4",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-001/video.mp4"
                },
                {
                  "type": "text/plain",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-001/video.m3u8"
                }
              ]
            },
            {
              "id": "549-002-2",
              "langId": "en",
              "siteId": "preop",
              "name": "TURP - Transurethral Resection of the Prostate",
              "translations": [
                {
                  "langId": "en",
                  "name": "TURP Laser vaporization",
                  "content": "TURP Laser vaporization",
                  "type": "application/json",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-002-2"
                },
                {
                  "langId": "es",
                  "name": "Vaporización Laser de la Próstata",
                  "content": "Vaporización Laser de la Próstata",
                  "type": "application/json",
                  "href": "http://api.medselfed.com/v1/es/procedures/549-002-2"
                }
              ],
              "links": [
                {
                  "type": "application/json",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-002-2"
                },
                {
                  "type": "image/jpg",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-002-2/image.jpg"
                },
                {
                  "type": "video/mp4",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-002-2/video.mp4"
                },
                {
                  "type": "text/plain",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-002-2/video.m3u8"
                }
              ]
            },
            {
              "id": "549-002-1",
              "langId": "en",
              "siteId": "preop",
              "name": "TURP Laser vaporization",
              "translations": [
                {
                  "langId": "en",
                  "name": "TURP Laser vaporization",
                  "content": "TURP Laser vaporization",
                  "type": "application/json",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-002-1"
                },
                {
                  "langId": "es",
                  "name": "Vaporización Laser de la Próstata",
                  "content": "Vaporización Laser de la Próstata",
                  "type": "application/json",
                  "href": "http://api.medselfed.com/v1/es/procedures/549-002-1"
                }
              ],
              "links": [
                {
                  "type": "application/json",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-002-1"
                },
                {
                  "type": "image/jpg",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-002-1/image.jpg"
                },
                {
                  "type": "video/mp4",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-002-1/video.mp4"
                },
                {
                  "type": "text/plain",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-002-1/video.m3u8"
                }
              ]
            },
            {
              "id": "549-004-1",
              "langId": "en",
              "siteId": "preop",
              "name": "Transurethral Resection of Bladder Tumor, Female",
              "translations": [],
              "links": [
                {
                  "type": "application/json",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-004-1"
                },
                {
                  "type": "image/jpg",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-004-1/image.jpg"
                },
                {
                  "type": "video/mp4",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-004-1/video.mp4"
                },
                {
                  "type": "text/plain",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-004-1/video.m3u8"
                }
              ]
            },
            {
              "id": "549-004-2",
              "langId": "en",
              "siteId": "preop",
              "name": "Transurethral Resection of Bladder Tumor, Male",
              "translations": [],
              "links": [
                {
                  "type": "application/json",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-004-2"
                },
                {
                  "type": "image/jpg",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-004-2/image.jpg"
                },
                {
                  "type": "video/mp4",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-004-2/video.mp4"
                },
                {
                  "type": "text/plain",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-004-2/video.m3u8"
                }
              ]
            },
            {
              "id": "549-005-1",
              "langId": "en",
              "siteId": "preop",
              "name": "Radical Prostatectomy, Laparoscopic",
              "translations": [],
              "links": [
                {
                  "type": "application/json",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-005-1"
                },
                {
                  "type": "image/jpg",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-005-1/image.jpg"
                },
                {
                  "type": "video/mp4",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-005-1/video.mp4"
                },
                {
                  "type": "text/plain",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-005-1/video.m3u8"
                }
              ]
            },
            {
              "id": "549-005-2",
              "langId": "en",
              "siteId": "preop",
              "name": "Radical Retropubic Prostatectomy, Open",
              "translations": [],
              "links": [
                {
                  "type": "application/json",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-005-2"
                },
                {
                  "type": "image/jpg",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-005-2/image.jpg"
                },
                {
                  "type": "video/mp4",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-005-2/video.mp4"
                },
                {
                  "type": "text/plain",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-005-2/video.m3u8"
                }
              ]
            },
            {
              "id": "549-005-3",
              "langId": "en",
              "siteId": "preop",
              "name": "Radical Prostatectomy, Robot Assisted Laparoscopic",
              "translations": [],
              "links": [
                {
                  "type": "application/json",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-005-3"
                },
                {
                  "type": "image/jpg",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-005-3/image.jpg"
                },
                {
                  "type": "video/mp4",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-005-3/video.mp4"
                },
                {
                  "type": "text/plain",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-005-3/video.m3u8"
                }
              ]
            },
            {
              "id": "549-006",
              "langId": "en",
              "siteId": "preop",
              "name": "Transrectal Ultrasound and Prostate Biopsy",
              "translations": [
                {
                  "langId": "en",
                  "name": "Transrectal Ultrasound and Prostate Biopsy",
                  "content": "Transrectal Ultrasound and Prostate Biopsy",
                  "type": "application/json",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-006"
                },
                {
                  "langId": "es",
                  "name": "Ultrasonido Transrectal y Biopsia de Próstata",
                  "content": "Ultrasonido Transrectal y Biopsia de Próstata",
                  "type": "application/json",
                  "href": "http://api.medselfed.com/v1/es/procedures/549-006"
                }
              ],
              "links": [
                {
                  "type": "application/json",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-006"
                },
                {
                  "type": "image/jpg",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-006/image.jpg"
                },
                {
                  "type": "video/mp4",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-006/video.mp4"
                },
                {
                  "type": "text/plain",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-006/video.m3u8"
                }
              ]
            },
            {
              "id": "549-007",
              "langId": "en",
              "siteId": "preop",
              "name": "Inflatable Penile Implant",
              "translations": [],
              "links": [
                {
                  "type": "application/json",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-007"
                },
                {
                  "type": "image/jpg",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-007/image.jpg"
                },
                {
                  "type": "video/mp4",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-007/video.mp4"
                },
                {
                  "type": "text/plain",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-007/video.m3u8"
                }
              ]
            },
            {
              "id": "549-008",
              "langId": "en",
              "siteId": "preop",
              "name": "Mesh Sling Procedure for Stress Urinary Incontinence (Female)",
              "translations": [],
              "links": [
                {
                  "type": "application/json",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-008"
                },
                {
                  "type": "image/jpg",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-008/image.jpg"
                },
                {
                  "type": "video/mp4",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-008/video.mp4"
                },
                {
                  "type": "text/plain",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-008/video.m3u8"
                }
              ]
            },
            {
              "id": "549-009-1",
              "langId": "en",
              "siteId": "preop",
              "name": "Catheter and Drainage Bag Care - Male",
              "translations": [],
              "links": [
                {
                  "type": "application/json",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-009-1"
                },
                {
                  "type": "image/jpg",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-009-1/image.jpg"
                },
                {
                  "type": "video/mp4",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-009-1/video.mp4"
                },
                {
                  "type": "text/plain",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-009-1/video.m3u8"
                }
              ]
            },
            {
              "id": "549-009-2",
              "langId": "en",
              "siteId": "preop",
              "name": "Catheter and Drainage Bag Care - Female",
              "translations": [],
              "links": [
                {
                  "type": "application/json",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-009-2"
                },
                {
                  "type": "image/jpg",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-009-2/image.jpg"
                },
                {
                  "type": "video/mp4",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-009-2/video.mp4"
                },
                {
                  "type": "text/plain",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-009-2/video.m3u8"
                }
              ]
            },
            {
              "id": "549-012-2",
              "langId": "en",
              "siteId": "preop",
              "name": "Ureteral Stent Instructions - Male",
              "translations": [
                {
                  "langId": "en",
                  "name": "Ureteral Stent Instructions - Male",
                  "content": "Ureteral Stent Instructions - Male",
                  "type": "application/json",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-012-2"
                },
                {
                  "langId": "es",
                  "name": "Instrucciones de Stent Uretral - hombre",
                  "content": "Instrucciones de Stent Uretral - hombre",
                  "type": "application/json",
                  "href": "http://api.medselfed.com/v1/es/procedures/549-012-2"
                }
              ],
              "links": [
                {
                  "type": "application/json",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-012-2"
                },
                {
                  "type": "image/jpg",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-012-2/image.jpg"
                },
                {
                  "type": "video/mp4",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-012-2/video.mp4"
                },
                {
                  "type": "text/plain",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-012-2/video.m3u8"
                }
              ]
            },
            {
              "id": "549-012-1",
              "langId": "en",
              "siteId": "preop",
              "name": "Ureteral Stent Instructions - Female",
              "translations": [
                {
                  "langId": "en",
                  "name": "Ureteral Stent Instructions - Female",
                  "content": "Ureteral Stent Instructions - Female",
                  "type": "application/json",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-012-1"
                },
                {
                  "langId": "es",
                  "name": "Instrucciones de Stent Uretral - mujer",
                  "content": "Instrucciones de Stent Uretral - mujer",
                  "type": "application/json",
                  "href": "http://api.medselfed.com/v1/es/procedures/549-012-1"
                }
              ],
              "links": [
                {
                  "type": "application/json",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-012-1"
                },
                {
                  "type": "image/jpg",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-012-1/image.jpg"
                },
                {
                  "type": "video/mp4",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-012-1/video.mp4"
                },
                {
                  "type": "text/plain",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-012-1/video.m3u8"
                }
              ]
            }
          ],
          "actions": [],
          "links": [],
          "entities": []
        }

# GET Procedures by Translation [/v1/{langid}/procedures]
The all procedures availible in the specified language identifier.  The API is useful for getting a list of the procedures in
different languages.  The default is US English or 'en'.  If you all procedures regardless of languages
you may use GET /v1/procedures

## Retrieve all Procedure Translations[GET]

The following example demostrates getting all of the spanish or 'es' procedures using curl.

`````
curl 'http://api.medselfed.com/v1/es/procedures?apikey=111223' 
`````

+ Parameters
    + langid (optional, string) ... the Procedure translation language identifier.
        + Default: `en`
    
+ Response 200 (application/json)
    + Headers

    + Body

         {
          "class": [
            "root"
          ],
          "properties": [
            {
              "id": "549-001",
              "langId": "en",
              "siteId": "preop",
              "name": "Vasectomy Surgery",
              "translations": [
                {
                  "langId": "en",
                  "name": "Vasectomy Surgery",
                  "content": "Vasectomy Surgery",
                  "type": "application/json",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-001"
                },
                {
                  "langId": "es",
                  "name": "Vasectomía",
                  "content": "Vasectomía",
                  "type": "application/json",
                  "href": "http://api.medselfed.com/v1/es/procedures/549-001"
                }
              ],
              "links": [
                {
                  "type": "application/json",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-001"
                },
                {
                  "type": "image/jpg",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-001/image.jpg"
                },
                {
                  "type": "video/mp4",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-001/video.mp4"
                },
                {
                  "type": "text/plain",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-001/video.m3u8"
                }
              ]
            },
            {
              "id": "549-002-2",
              "langId": "en",
              "siteId": "preop",
              "name": "TURP - Transurethral Resection of the Prostate",
              "translations": [
                {
                  "langId": "en",
                  "name": "TURP Laser vaporization",
                  "content": "TURP Laser vaporization",
                  "type": "application/json",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-002-2"
                },
                {
                  "langId": "es",
                  "name": "Vaporización Laser de la Próstata",
                  "content": "Vaporización Laser de la Próstata",
                  "type": "application/json",
                  "href": "http://api.medselfed.com/v1/es/procedures/549-002-2"
                }
              ],
              "links": [
                {
                  "type": "application/json",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-002-2"
                },
                {
                  "type": "image/jpg",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-002-2/image.jpg"
                },
                {
                  "type": "video/mp4",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-002-2/video.mp4"
                },
                {
                  "type": "text/plain",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-002-2/video.m3u8"
                }
              ]
            },
            {
              "id": "549-002-1",
              "langId": "en",
              "siteId": "preop",
              "name": "TURP Laser vaporization",
              "translations": [
                {
                  "langId": "en",
                  "name": "TURP Laser vaporization",
                  "content": "TURP Laser vaporization",
                  "type": "application/json",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-002-1"
                },
                {
                  "langId": "es",
                  "name": "Vaporización Laser de la Próstata",
                  "content": "Vaporización Laser de la Próstata",
                  "type": "application/json",
                  "href": "http://api.medselfed.com/v1/es/procedures/549-002-1"
                }
              ],
              "links": [
                {
                  "type": "application/json",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-002-1"
                },
                {
                  "type": "image/jpg",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-002-1/image.jpg"
                },
                {
                  "type": "video/mp4",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-002-1/video.mp4"
                },
                {
                  "type": "text/plain",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-002-1/video.m3u8"
                }
              ]
            },
            {
              "id": "549-004-1",
              "langId": "en",
              "siteId": "preop",
              "name": "Transurethral Resection of Bladder Tumor, Female",
              "translations": [],
              "links": [
                {
                  "type": "application/json",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-004-1"
                },
                {
                  "type": "image/jpg",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-004-1/image.jpg"
                },
                {
                  "type": "video/mp4",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-004-1/video.mp4"
                },
                {
                  "type": "text/plain",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-004-1/video.m3u8"
                }
              ]
            },
            {
              "id": "549-004-2",
              "langId": "en",
              "siteId": "preop",
              "name": "Transurethral Resection of Bladder Tumor, Male",
              "translations": [],
              "links": [
                {
                  "type": "application/json",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-004-2"
                },
                {
                  "type": "image/jpg",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-004-2/image.jpg"
                },
                {
                  "type": "video/mp4",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-004-2/video.mp4"
                },
                {
                  "type": "text/plain",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-004-2/video.m3u8"
                }
              ]
            },
            {
              "id": "549-005-1",
              "langId": "en",
              "siteId": "preop",
              "name": "Radical Prostatectomy, Laparoscopic",
              "translations": [],
              "links": [
                {
                  "type": "application/json",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-005-1"
                },
                {
                  "type": "image/jpg",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-005-1/image.jpg"
                },
                {
                  "type": "video/mp4",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-005-1/video.mp4"
                },
                {
                  "type": "text/plain",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-005-1/video.m3u8"
                }
              ]
            },
            {
              "id": "549-005-2",
              "langId": "en",
              "siteId": "preop",
              "name": "Radical Retropubic Prostatectomy, Open",
              "translations": [],
              "links": [
                {
                  "type": "application/json",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-005-2"
                },
                {
                  "type": "image/jpg",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-005-2/image.jpg"
                },
                {
                  "type": "video/mp4",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-005-2/video.mp4"
                },
                {
                  "type": "text/plain",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-005-2/video.m3u8"
                }
              ]
            },
            {
              "id": "549-005-3",
              "langId": "en",
              "siteId": "preop",
              "name": "Radical Prostatectomy, Robot Assisted Laparoscopic",
              "translations": [],
              "links": [
                {
                  "type": "application/json",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-005-3"
                },
                {
                  "type": "image/jpg",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-005-3/image.jpg"
                },
                {
                  "type": "video/mp4",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-005-3/video.mp4"
                },
                {
                  "type": "text/plain",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-005-3/video.m3u8"
                }
              ]
            },
            {
              "id": "549-006",
              "langId": "en",
              "siteId": "preop",
              "name": "Transrectal Ultrasound and Prostate Biopsy",
              "translations": [
                {
                  "langId": "en",
                  "name": "Transrectal Ultrasound and Prostate Biopsy",
                  "content": "Transrectal Ultrasound and Prostate Biopsy",
                  "type": "application/json",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-006"
                },
                {
                  "langId": "es",
                  "name": "Ultrasonido Transrectal y Biopsia de Próstata",
                  "content": "Ultrasonido Transrectal y Biopsia de Próstata",
                  "type": "application/json",
                  "href": "http://api.medselfed.com/v1/es/procedures/549-006"
                }
              ],
              "links": [
                {
                  "type": "application/json",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-006"
                },
                {
                  "type": "image/jpg",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-006/image.jpg"
                },
                {
                  "type": "video/mp4",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-006/video.mp4"
                },
                {
                  "type": "text/plain",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-006/video.m3u8"
                }
              ]
            },
            {
              "id": "549-007",
              "langId": "en",
              "siteId": "preop",
              "name": "Inflatable Penile Implant",
              "translations": [],
              "links": [
                {
                  "type": "application/json",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-007"
                },
                {
                  "type": "image/jpg",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-007/image.jpg"
                },
                {
                  "type": "video/mp4",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-007/video.mp4"
                },
                {
                  "type": "text/plain",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-007/video.m3u8"
                }
              ]
            },
            {
              "id": "549-008",
              "langId": "en",
              "siteId": "preop",
              "name": "Mesh Sling Procedure for Stress Urinary Incontinence (Female)",
              "translations": [],
              "links": [
                {
                  "type": "application/json",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-008"
                },
                {
                  "type": "image/jpg",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-008/image.jpg"
                },
                {
                  "type": "video/mp4",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-008/video.mp4"
                },
                {
                  "type": "text/plain",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-008/video.m3u8"
                }
              ]
            },
            {
              "id": "549-009-1",
              "langId": "en",
              "siteId": "preop",
              "name": "Catheter and Drainage Bag Care - Male",
              "translations": [],
              "links": [
                {
                  "type": "application/json",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-009-1"
                },
                {
                  "type": "image/jpg",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-009-1/image.jpg"
                },
                {
                  "type": "video/mp4",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-009-1/video.mp4"
                },
                {
                  "type": "text/plain",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-009-1/video.m3u8"
                }
              ]
            },
            {
              "id": "549-009-2",
              "langId": "en",
              "siteId": "preop",
              "name": "Catheter and Drainage Bag Care - Female",
              "translations": [],
              "links": [
                {
                  "type": "application/json",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-009-2"
                },
                {
                  "type": "image/jpg",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-009-2/image.jpg"
                },
                {
                  "type": "video/mp4",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-009-2/video.mp4"
                },
                {
                  "type": "text/plain",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-009-2/video.m3u8"
                }
              ]
            },
            {
              "id": "549-012-2",
              "langId": "en",
              "siteId": "preop",
              "name": "Ureteral Stent Instructions - Male",
              "translations": [
                {
                  "langId": "en",
                  "name": "Ureteral Stent Instructions - Male",
                  "content": "Ureteral Stent Instructions - Male",
                  "type": "application/json",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-012-2"
                },
                {
                  "langId": "es",
                  "name": "Instrucciones de Stent Uretral - hombre",
                  "content": "Instrucciones de Stent Uretral - hombre",
                  "type": "application/json",
                  "href": "http://api.medselfed.com/v1/es/procedures/549-012-2"
                }
              ],
              "links": [
                {
                  "type": "application/json",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-012-2"
                },
                {
                  "type": "image/jpg",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-012-2/image.jpg"
                },
                {
                  "type": "video/mp4",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-012-2/video.mp4"
                },
                {
                  "type": "text/plain",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-012-2/video.m3u8"
                }
              ]
            },
            {
              "id": "549-012-1",
              "langId": "en",
              "siteId": "preop",
              "name": "Ureteral Stent Instructions - Female",
              "translations": [
                {
                  "langId": "en",
                  "name": "Ureteral Stent Instructions - Female",
                  "content": "Ureteral Stent Instructions - Female",
                  "type": "application/json",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-012-1"
                },
                {
                  "langId": "es",
                  "name": "Instrucciones de Stent Uretral - mujer",
                  "content": "Instrucciones de Stent Uretral - mujer",
                  "type": "application/json",
                  "href": "http://api.medselfed.com/v1/es/procedures/549-012-1"
                }
              ],
              "links": [
                {
                  "type": "application/json",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-012-1"
                },
                {
                  "type": "image/jpg",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-012-1/image.jpg"
                },
                {
                  "type": "video/mp4",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-012-1/video.mp4"
                },
                {
                  "type": "text/plain",
                  "href": "http://api.medselfed.com/v1/en/procedures/549-012-1/video.m3u8"
                }
              ]
            }
          ],
          "actions": [],
          "links": [],
          "entities": []
        }


## Get Procedures By Id [/v1/procedures/{id}]
A single Procedure presentation. This is the central resource in the Procedures API. It represents a single presentation.

The Procedures resource has the following attributes: 

- id
- location
- name
- title
- string
- h1
- h2

Example Request

To make a request to the API run the following command at a terminal prompt.

`````
curl 'http://api.medselfed.com/v1/procedures/549-001?apikey=111223' 
`````


+ Parameters
    + id (string) ... Procedure identifier in form of alpha - number hash.

+ Model (application/json)

    application/json is the media type of the Procedure resource. In addition to representing its properties, it offers offers affordances in the form of links of available media type.

    + Headers

    + Body

        {
          "class": [
            "procedures"
          ],
          "properties": {
            "id": "549-001",
            "langId": "en",
            "location": "online",
            "translations": [
              {
                "langId": "es",
                "name": "Vasectomía",
                "content": "Vasectomía",
                "type": "application/json",
                "href": "http://api.medselfed.com/v1/es/procedures/549-001"
              }
            ],
            "h1": "Vasectomy Surgery",
            "name": "Vasectomy Surgery",
            "title": "Vasectomy Surgery ",
            "string": "Vasectomy_Surgery",
            "links": []
          },
          "actions": [],
          "links": [
            {
              "type": "application/json",
              "href": "http://api.medselfed.com/v1/en/procedures/549-001"
            },
            {
              "type": "image/jpg",
              "href": "http://api.medselfed.com/v1/en/procedures/549-001/image.jpg"
            },
            {
              "type": "video/mp4",
              "href": "http://api.medselfed.com/v1/en/procedures/549-001/video.mp4"
            },
            {
              "type": "text/plain",
              "href": "http://api.medselfed.com/v1/en/procedures/549-001/video.m3u8"
            }
          ],
          "entities": []
        }

### Retrieve a Single Procedure [GET]

+ Response 200
    
    [Get Procedures By Id][]



## Group Patients API

The MedSelfEd Patient API provides app developers affordances to synchronize 
medical procedure video playback experiences across devices.  Developers may 
use this API to create new patient playback identifiers, sign in, maintain a 
profile and share their viewing history other patients and using popular social 
networks.

Associating the playback experience to a patient can be done using this API.  
You may also invoke it's functionality by appending the patient identifier to a content request. 

If wish to prescribe patient identifier “mynewpatient-12345”  see the “Gastric Bypass - Laparoscopic Surgery”, the following request would allow a patient playback widget to be customized for the prescribed MedSelfEd Procedure video.   

    http://api.medselfed.com/v1/procedures/{prodid}/video?apikey={apikey}&patientid={patientid}

For example: 
* prodid :  __444__ - Gastric Bypass - Laparoscopic Surgery
* apikey : __yourapikey__ - The api key associated to your app 
* patient : __mynewpatient-12345__ - The patient identifier given by your app

In code:
    
    curl 'http://api.medselfed.com/v1/procedures/444/video?apikey=7K9UKcnY&patientid=mynewpatient-12345'

If the playback activity request is successful you will then retrieve the content as usual.  Later on, when the patient would like to review the content again from the comfort of thier home they can use the provided identifier to recall the previously reviewed content.

    curl 'http://api.medselfed.com/v1/patients/mynewpatient-12345/activities'
    
Patient playback identifiers are purposely kept anonymous but are unique to your app. 

## All Patient identifiers [/v1/patients]

This resource group allows app developers to review all Patient playback identifiers currently associated to thier app.

### Get all Patient Identifiers [GET]

The you may use the __GET__ HTTP verb to retrieve a collection of patient playback identifiers provided by your app.

+ Response 200 (application/json)

        {
            "patients": [
                {
                    "patientid": 12345,
                    "uuid": "278000aa-ba48-11e5-a69b-a50b70e692ce"
                },
                {
                    "patientid": “your-id“,
                    "uuid": "a3fff7ca-ba66-11e5-8c20-8b8b93ab505a"
                }
            ]
        }

### Create a new Patient Identifier [POST]

You may create new patient identifiers using the __POST__ HTTP verb and providing a patientid
value in the request body.

+ Request (application/json)

        {
          "patientid":"mynewpatient"
        }

+ Response 201 (application/json)

    + Headers

            Location: /v1/patients/5543

    + Body

            {
                "patientid": "mynewpatient",
                "uuid": "da51525a-baf3-11e5-995d-172ca931ebdb",
                "created": 1452799220725,
                "modified": 1452812441542
            }
            
## Patient Identifiers [/v1/patients/{patientid}]
This resource group allows app developers to review individual Patient playback identifiers.

+ Parameters

    + patientid: `mynewpatient` (string, required) - Patient playback identifier

### Get Patient Access Token [GET]

To get a existing patient playback access token simply provide the patient identifier to generate a new access token.

+ Response 200 (application/json)

            {
                "patientid": "5543",
                "uuid": "c6cf4c9a-ba81-11e5-8e33-65f5f26e4a2a",
                "access_token": "YWMtI-b1crsTEeWgAHFr9Lk0VgAAAVJmbmuRbBrIXYdK12c3pomESIZ3fvfhqOA"
            }


## Patient Activities [/v1/patients/{patientid}/activities]
This resource group allows app developers to review individual Patient playback activities.

+ Parameters

    + patientid: `mynewpatient` (string, required) - Patient playback identifier

### Get Activity by Patient Id[GET]

To get existing playback activity for the provided patient identifiers.  

+ Response 200 (application/json)

            {
                "patientid": "5543",
                "activities": [
                    {
                        "content": "video",
                        "verb": "get",
                        "href": "http://api.medselfed.com/v1/procedures/549-002-2/video.m3u8",
                        "created": 1452801662433
                    }
                ]
            }